/// Loads per-word English glosses for a surah.
///
/// The bundled assets are generated by `tools/build_word_by_word.dart`, which
/// guarantees that the gloss list for an ayah has exactly one entry per word
/// of [segmentArabicWords] applied to that ayah's standard Uthmani text. The
/// reader therefore indexes by word position instead of trying to reconcile
/// two different word numbering schemes at runtime.
///
/// An empty gloss means the word continues the previous gloss as one phrase,
/// as in بَعْدَ مَا -> "after what". Use [glossPhraseAt] to resolve that.
///
/// Gloss text derives from "The Glorious Qur'an: Word-for-Word Translation to
/// Facilitate Learning of Qur'anic Arabic" by Dr. Shehnaz Shaikh and
/// Ms. Kausar Khatri.
library;

import 'dart:convert';

import 'package:flutter/foundation.dart';
import 'package:flutter/services.dart' show rootBundle;

import '../data/asset_paths.dart';

/// The span of words that share one gloss.
///
/// Most phrases cover a single word. A phrase covers several when the source
/// glosses them together, so highlighting the whole span is what matches the
/// English shown to the reader.
@immutable
class GlossPhrase {
  /// Index of the first word in the phrase.
  final int firstWord;

  /// Index of the last word in the phrase, inclusive.
  final int lastWord;

  /// The English gloss for the phrase.
  final String gloss;

  const GlossPhrase({
    required this.firstWord,
    required this.lastWord,
    required this.gloss,
  });

  /// Whether the phrase spans more than one Arabic word.
  bool get isMultiWord => lastWord > firstWord;

  @override
  bool operator ==(Object other) =>
      other is GlossPhrase &&
      other.firstWord == firstWord &&
      other.lastWord == lastWord &&
      other.gloss == gloss;

  @override
  int get hashCode => Object.hash(firstWord, lastWord, gloss);
}

/// Resolves the phrase covering [wordIndex] within [glosses].
///
/// Walks back to the word that owns the gloss and forward over any words that
/// continue it. Returns `null` when [wordIndex] is out of range.
GlossPhrase? glossPhraseAt(List<String> glosses, int wordIndex) {
  if (wordIndex < 0 || wordIndex >= glosses.length) return null;

  var first = wordIndex;
  while (first > 0 && glosses[first].isEmpty) {
    first--;
  }
  if (glosses[first].isEmpty) return null;

  var last = wordIndex;
  while (last + 1 < glosses.length && glosses[last + 1].isEmpty) {
    last++;
  }

  return GlossPhrase(firstWord: first, lastWord: last, gloss: glosses[first]);
}

/// Provides word-by-word glosses for a surah, keyed by ayah number.
class WordByWordRepository {
  const WordByWordRepository();

  /// Completed and in-flight loads, so concurrent callers share one decode
  /// and revisiting a surah costs nothing.
  static final Map<int, Future<Map<int, List<String>>>> _cache = {};

  /// Returns `{ ayahNumber: [glossPerWord] }` for [surahId].
  ///
  /// Returns an empty map if the asset is missing or malformed: word-by-word
  /// is an optional study aid, so a data problem must degrade to plain
  /// reading rather than break the reader.
  Future<Map<int, List<String>>> loadSurah(int surahId) {
    return _cache.putIfAbsent(surahId, () => _load(surahId));
  }

  static Future<Map<int, List<String>>> _load(int surahId) async {
    try {
      final raw = await rootBundle.loadString(
        AssetPaths.quranWordByWordEnglish(surahId),
      );
      final decoded = json.decode(raw) as Map<String, dynamic>;
      return {
        for (final entry in decoded.entries)
          int.parse(entry.key): (entry.value as List)
              .map((gloss) => gloss.toString())
              .toList(growable: false),
      };
    } catch (error) {
      debugPrint('Word-by-word glosses unavailable for surah $surahId: $error');
      return const {};
    }
  }

  /// Clears the session cache. Tests only.
  @visibleForTesting
  static void resetCache() => _cache.clear();
}
